name = "Typst"
grammar = "typst"
path_suffixes = ["typ", "typst"]
line_comments = ["// "]
tab_size = 2
brackets = [
    { start = "(", end = ")", close = true, newline = true },
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "$", end = "$", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "*", end = "*", close = false, newline = false, surround = true },
    { start = "_", end = "_", close = false, newline = false, surround = true },
    { start = "`", end = "`", close = false, newline = false, surround = true },
]
